name: Bug report
description: Report a reproducible defect
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please include steps to reproduce and expected behavior.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/commit
      placeholder: e.g. main@abcdef1
