name: Feature request
description: Propose an enhancement
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: What user/business problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe the approach at a high level.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
